<?php
namespace VuloPilot\SeoVisibility;

defined( 'ABSPATH' ) || exit;

/**
 * Restyles WordPress core's own native `/wp-sitemap.xml` browser view
 * (`WP_Sitemaps_Stylesheet`, wp-includes/sitemaps) to match the reference mockup.
 *
 * @class       SitemapStylesheet class
 * @version     1.0.0
 * @author      VuloLabs
 */
class SitemapStylesheet {

	/**
	 * Compiled file, relative to the plugin folder.
	 *
	 * @var string
	 */
	private const STYLE_FILE = 'assets/styles/public/vulopilot-sitemap-stylesheet.min.css';

	/**
	 * SitemapStylesheet constructor.
	 */
	public function __construct() {
		add_filter( 'wp_sitemaps_stylesheet_css', array( $this, 'filter_stylesheet_css' ) );
		add_filter( 'wp_sitemaps_stylesheet_index_content', array( $this, 'filter_index_stylesheet_content' ) );
	}

	/**
	 * Real CSS-only restyle - applies to core's own existing markup structure
	 * (`#sitemap__header`/`#sitemap__table`) unchanged.
	 *
	 * @param string $css Core's own default CSS for the sitemap.
	 * @return string
	 */
	public function filter_stylesheet_css( $css ) {
		$path = VuloPilot()->plugin_path . self::STYLE_FILE;

		if ( ! file_exists( $path ) ) {
			return $css;
		}

        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- reads this plugin's own built stylesheet, not user input.
		return $css . (string) file_get_contents( $path );
	}

	/**
	 * Address of the compiled file for the index page, with the plugin
	 * version appended. Empty when the file has not been built.
	 *
	 * @return string
	 */
	private function get_stylesheet_url(): string {
		if ( ! file_exists( VuloPilot()->plugin_path . self::STYLE_FILE ) ) {
			return '';
		}

		wp_register_style(
			'vulopilot-sitemap-stylesheet',
			VuloPilot()->plugin_url . self::STYLE_FILE,
			array(),
			VuloPilot()->version
		);

		$style = wp_styles()->registered['vulopilot-sitemap-stylesheet'];

		return add_query_arg( 'ver', $style->ver, $style->src );
	}

	/**
	 * Full real XSL override for the sitemap INDEX page only (the top-level `/wp-
	 * sitemap.xml` listing child sitemaps).
	 *
	 * @return string
	 */
	public function filter_index_stylesheet_content() {
		$title       = esc_xml( __( 'XML Sitemap', 'vulopilot' ) );
		$description = esc_xml( __( 'This XML Sitemap is generated by WordPress to make your content more visible for search engines.', 'vulopilot' ) );
		$learn_more  = sprintf(
			'<a href="%s">%s</a>',
			esc_url( __( 'https://www.sitemaps.org/', 'vulopilot' ) ),
			esc_xml( __( 'Learn more about XML sitemaps.', 'vulopilot' ) )
		);

		$text = sprintf(
			/* translators: %s: real count of child sitemaps in this index. */
			esc_xml( __( 'This XML Sitemap Index file contains %s sitemaps.', 'vulopilot' ) ),
			'<xsl:value-of select="count( sitemap:sitemapindex/sitemap:sitemap )" />'
		);

		$lang    = get_language_attributes( 'html' );
		$url     = esc_xml( __( 'Sitemap', 'vulopilot' ) );
		$lastmod = esc_xml( __( 'Last Modified', 'vulopilot' ) );
		$css_url = $this->get_stylesheet_url();
		$link    = '' !== $css_url
			? '<xsl:element name="link"><xsl:attribute name="rel">stylesheet</xsl:attribute><xsl:attribute name="href">' . esc_xml( esc_url( $css_url ) ) . '</xsl:attribute></xsl:element>'
			: '';

		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<xsl:stylesheet
		version=\"1.0\"
		xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"
		xmlns:sitemap=\"http://www.sitemaps.org/schemas/sitemap/0.9\"
		exclude-result-prefixes=\"sitemap\"
		>

	<xsl:output method=\"html\" encoding=\"UTF-8\" indent=\"yes\" />

	<xsl:template match=\"/\">
		<html {$lang}>
			<head>
				<title>{$title}</title>
				{$link}
			</head>
			<body>
				<div id=\"sitemap\">
					<div id=\"sitemap__header\">
						<h1>{$title}</h1>
						<p>{$description}</p>
						<p>{$learn_more}</p>
					</div>
					<div id=\"sitemap__content\">
						<p class=\"text\">{$text}</p>
						<table id=\"sitemap__table\">
							<thead>
								<tr>
									<th class=\"loc\">{$url}</th>
									<th class=\"lastmod\">{$lastmod}</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select=\"sitemap:sitemapindex/sitemap:sitemap\">
									<tr>
										<td class=\"loc\"><a href=\"{sitemap:loc}\"><xsl:value-of select=\"sitemap:loc\" /></a></td>
										<td class=\"lastmod\"><xsl:value-of select=\"sitemap:lastmod\" /></td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>

";
	}
}
